config/routes.rb
DailyRead::Application.routes.draw do
  resources :passages

  root 'pages#index'

  

end

app/models/passage.rb
class Passage < ActiveRecord::Base

  scope :for_date, ->(date) {
    where([
      "read_on BETWEEN :beginning_of_day AND :end_of_day",
      { beginning_of_day: date.beginning_of_day, end_of_day: date.end_of_day }
    ])
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @passage = Passage.for_date(Time.zone.now).first
  end
end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  before_action :set_passage, only: [:show, :edit, :update, :destroy]

  # GET /passages
  # GET /passages.json
  def index
    @passages = Passage.all
  end

  # GET /passages/1
  # GET /passages/1.json
  def show
  end

  # GET /passages/new
  def new
    @passage = Passage.new
  end

  # GET /passages/1/edit
  def edit
  end

  # POST /passages
  # POST /passages.json
  def create
    @passage = Passage.new(passage_params)

    respond_to do |format|
      if @passage.save
        format.html { redirect_to @passage, notice: 'Passage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @passage }
      else
        format.html { render action: 'new' }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passages/1
  # PATCH/PUT /passages/1.json
  def update
    respond_to do |format|
      if @passage.update(passage_params)
        format.html { redirect_to @passage, notice: 'Passage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passages/1
  # DELETE /passages/1.json
  def destroy
    @passage.destroy
    respond_to do |format|
      format.html { redirect_to passages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passage
      @passage = Passage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passage_params
      params.require(:passage).permit(:name, :text, :read_on)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert-success"
    when :error then "alert-danger"
    when :alert then "alert-warning"
    else "alert-info"
    end
  end

  def is_edit_action?
    action_name == "edit"
  end

  module BootstrapExtension
    FORM_CONTROL_CLASS = "form-control"

    def text_field(name, value = nil, options = {})
      class_name = options[:class]
      if class_name.nil?
        options[:class] = FORM_CONTROL_CLASS
      else
        options[:class] << " #{FORM_CONTROL_CLASS}" if
        " #{class_name} ".index(" #{FORM_CONTROL_CLASS} ").nil?
      end

      super
    end

    alias_method :email_field, :text_field
    alias_method :password_field, :text_field
  end

  include BootstrapExtension
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |level, message|
  .container
    #flash_message{ class: "alert #{flash_class(level)} alert-dismissable" }
      %p.message_content{ :style => "display:inline" }= message
      %a{ class: "close", href: "#", onclick: "return false;" } ×

:javascript
  $('a.close').on('click', function() {
    $(this).parent().fadeOut();
  });

  var flash_fade_out = function() {
    $('.close').parent().fadeOut();
  }

  setTimeout("flash_fade_out();", 5000);

app/views/layouts/_header.html.haml
.navbar.navbar-inverse.navbar-fixed-top{ "role" => "navigation" }
  .container
    .navbar-header
      %button.navbar-toggle{ "data-toggle" => "collapse", "data-target" => "#navbar_content" }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: root_path, style: "color:white;font-size:32px;" }
        Daily Read

    #navbar_content.collapse.navbar-collapse
      -#%ul.nav.navbar-nav
        %li{ class: @tab == "home" ? "active" : "" }
          = link_to "Home", root_path

      -#%ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li#account_menu.dropdown
            %a#account_link.dropdown-toggle{ href: "#", onclick: "return false;", "role" => "button", "data-toggle" => "dropdown"}
              Account
              %b.caret
            %ul.dropdown-menu{ "role" => "menu", "aria-labelledby" => "account_link" }
              %li{ "role" => "presentation" }
                %a{ "role" => "menuitem", "tabindex" => "-1", href: dashboard_path } Dashboard
              - if current_organization.present?
                - if current_user.is_support?
                  %li{ "role" => "presentation" }
                    %a{ "role" => "menuitem", "tabindex" => "-1", href: admin_path } Admin
                - if current_user.is_admin? || current_user.is_support?
                  %li{ "role" => "presentation" }
                    %a{ "role" => "menuitem", "tabindex" => "-1", href: users_path } Manage users
              %li{ "role" => "presentation" }
                %a{ "role" => "menuitem", "tabindex" => "-1", href: edit_user_path(current_user.id) } My account
              %li.divider{ "role" => "presentation" }
                %li{ "role" => "presentation" }
                  %a{ "role" => "menuitem", "tabindex" => "-1", href: destroy_user_session_path, "data-method" => "delete" } Sign out
        - else
          %li{ "role" => "presentation" }
            %a{ "role" => "menuitem", "tabindex" => "-1", href: new_registration_path(:user) } Sign up
          %li{ "role" => "presentation" }
            %a{ "role" => "menuitem", "tabindex" => "-1", href: user_session_path } Sign in

:javascript
  $(document).ready(function() {
    $('.dropdown-toggle').dropdown()
  })

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:charset => "utf-8"}/

    %title Daily Read

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true

    = csrf_meta_tags

    <link rel="apple-touch-icon" sizes="57x57" href="/assets/favicons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/assets/favicons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/assets/favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/assets/favicons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/assets/favicons/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/assets/favicons/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/favicons/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/favicons/apple-touch-icon-152x152.png">
    <link rel="icon" type="image/png" href="/assets/favicons/favicon-196x196.png" sizes="196x196">
    <link rel="icon" type="image/png" href="/assets/favicons/favicon-160x160.png" sizes="160x160">
    <link rel="icon" type="image/png" href="/assets/favicons/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/assets/favicons/favicon-16x16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="/assets/favicons/favicon-32x32.png" sizes="32x32">
    <meta name="msapplication-TileColor" content="#ff0000">
    <meta name="msapplication-TileImage" content="/assets/favicons/mstile-144x144.png">

  %body
    = render :partial => "layouts/header"

    #flash_message
      = render :partial => 'layouts/flash', locals: { flash: flash }

    .container
      = yield

app/views/layouts/email_template.html.haml
<!DOCTYPE html>
%html
  %head
    :css
      table {
        width: 650px;
        background-color: #1C9E79;
        padding: 10px 0px; }
        table tr td {
          padding: 10px 15px 20px 15px;
          font-family: Helvetica, Arial, sans-serif;

          text-align: left; }
          table tr td table {
            width: 640px;
            background-color: #fdfdfd;
          table tr td p.footer {
            color: white;
            font-size: 0.9em; }
            table tr td p.footer a {
              color: white; }
          table tr h1 {
            color: #073D3;
            font-size: 1.5em;
            letter-spacing: -1px;
            line-height: normal; }
          table table {
            padding: 20px 0px; }
            table table .closing {
              margin: 0; }

      .light_green {
        color: #1C9E79;
      }

      .light_green_background {
        background-color: #1C9E79;
      }

      .dark_green {
        color: #073D30;
      }

      .dark_green_background {
        background-color: #073D30;
      }

      .white {
        color: white;
      }

  %body
    %table
      %tr
        %td
          = render :partial => 'user_mailer/email_header'
          %table
            %tr
              %td
                = yield
      %tr
        %td
          = render :partial => 'user_mailer/email_footer'

app/views/pages/index.html.haml
#content
  - if @passage.present?
    %h1= @passage.name
    %h3
      Read on:
      = @passage.read_on.to_s(:date)
    %p= raw @passage.content
  - else
    %h3 Sorry, no passages for today.

:javascript

app/views/passages/_form.html.haml
= form_for @passage do |f|
  - if @passage.errors.any?
    #error_explanation
      %h2= "#{pluralize(@passage.errors.count, "error")} prohibited this passage from being saved:"
      %ul
        - @passage.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :read_on
    = f.datetime_select :read_on
  .actions
    = f.submit 'Save'

app/views/passages/edit.html.haml
%h1 Editing passage

= render 'form'

= link_to 'Show', @passage
\|
= link_to 'Back', passages_path

app/views/passages/index.html.haml
%h1 Listing passages

%table
  %tr
    %th Name
    %th Text
    %th Read on
    %th
    %th
    %th

  - @passages.each do |passage|
    %tr
      %td= passage.name
      %td= passage.text
      %td= passage.read_on
      %td= link_to 'Show', passage
      %td= link_to 'Edit', edit_passage_path(passage)
      %td= link_to 'Destroy', passage, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Passage', new_passage_path

app/views/passages/new.html.haml
%h1 New passage

= render 'form'

= link_to 'Back', passages_path

app/views/passages/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @passage.name
%p
  %b Text:
  = @passage.text
%p
  %b Read on:
  = @passage.read_on

= link_to 'Edit', edit_passage_path(@passage)
\|
= link_to 'Back', passages_path